{% set version = "1.5.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-flexclust
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/flexclust_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/flexclust/flexclust_{{ version }}.tar.gz
  sha256: f0fb5f2c338b5b4d310cdbe6b55b7e49d3ffc625002390a145dd5abd2f495fa3

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("c") }}                # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-class
    - r-lattice
    - r-modeltools
  run:
    - r-base
    - r-class
    - r-lattice
    - r-modeltools

test:
  commands:
    - $R -e "library('flexclust')"           # [not win]
    - "\"%R%\" -e \"library('flexclust')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=flexclust
  license: GPL-2.0-only
  summary: The main function kcca implements a general framework for k-centroids cluster analysis supporting arbitrary distance measures and centroid computation. Further cluster methods include hard competitive learning, neural gas, and QT clustering. There are numerous visualization methods for cluster results (neighborhood
    graphs, convex cluster hulls, barcharts of centroids, ...), and bootstrap methods for the analysis of cluster stability.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: flexclust
# Version: 1.4-0
# Date: 2018-09-20
# Authors@R: c(person(given="Friedrich", family="Leisch", email="Friedrich.Leisch@R-project.org", role=c("aut", "cre"), comment = c(ORCID = "0000-0001-7278-1983")), person(given="Evgenia", family="Dimitriadou", role="ctb"), person("Bettina", "Gruen", role = "aut", comment = c(ORCID = "0000-0001-7265-4773")))
# Title: Flexible Cluster Algorithms
# Depends: R (>= 2.14.0), graphics, grid, lattice, modeltools
# Imports: methods, parallel, stats, stats4, class
# Suggests: ellipse, clue, cluster, seriation, skmeans
# Description: The main function kcca implements a general framework for k-centroids cluster analysis supporting arbitrary distance measures and centroid computation. Further cluster methods include hard competitive learning, neural gas, and QT clustering. There are numerous visualization methods for cluster results (neighborhood graphs, convex cluster hulls, barcharts of centroids, ...), and bootstrap methods for the analysis of cluster stability.
# License: GPL-2
# LazyLoad: yes
# NeedsCompilation: yes
# Packaged: 2018-09-20 11:08:49 UTC; leisch
# Author: Friedrich Leisch [aut, cre] (<https://orcid.org/0000-0001-7278-1983>), Evgenia Dimitriadou [ctb], Bettina Gruen [aut] (<https://orcid.org/0000-0001-7265-4773>)
# Maintainer: Friedrich Leisch <Friedrich.Leisch@R-project.org>
# Repository: CRAN
# Date/Publication: 2018-09-24 22:50:03 UTC
