# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ew6Vd57eVwRKz9MXjPJsmHhLxEfheyxqcTom0NP5YvApMIqo+o3Xty8c2gMmvia3JZs0vgxKQ/iIcaHmmdSGeq9IPgnW3sQONNpC97Luek0DqGPXK3iLWb8UuyiN0v64QLl7w5EtEH43jX/WyER74PiEtwAFlR3iHZredzc3qUzu+jCj8iX84r6TIh8nuZpxFJlE5m2Id+hcrMwa1k91NwXg1mfzlMdpX4A/rV2hlIc7l5qB2AVBHPFQ6BpMneNX32Vq8mV3j0g01s63BBV/y1YjM6nfwsgH0jiuGBjmb3cBTf6TEuUs0gyq7m3oPl1QXeQBFGTeKDxuWalEOZnOAIqmVfzN8ztCkgSnishEVfcrgE0y7ZstmFQysRg19Ex1zK3vU0JLA98wPUrE9Bsj9VnKgqGdcrrS9lOyIImqTbfyE56hyS/t2Kw33AtCe5Wy4a8pljwjVXHmVsXVOmkOjd1pI3P1QzIO15GvHfoUUFaRC8GuNpNNfAzEO1ROvlCbrksms6Aw/ies7jQL7WyJxAYhpsyE8aCLpT5wM1FzTz3zd+Sw31oBdbyCNLD+Ar82KDBwJQ25503/ZMiZ6Cs8HbHklQC/CoyDEoDovv1ROBFVppOdjVFxC90Ucq3SZvZPao3rcZP3Nw/ObucvhOG2wtO/f4AuNleNvj/JPNQu7WA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
