travis:
  secure:
    BINSTAR_TOKEN: ew6Vd57eVwRKz9MXjPJsmHhLxEfheyxqcTom0NP5YvApMIqo+o3Xty8c2gMmvia3JZs0vgxKQ/iIcaHmmdSGeq9IPgnW3sQONNpC97Luek0DqGPXK3iLWb8UuyiN0v64QLl7w5EtEH43jX/WyER74PiEtwAFlR3iHZredzc3qUzu+jCj8iX84r6TIh8nuZpxFJlE5m2Id+hcrMwa1k91NwXg1mfzlMdpX4A/rV2hlIc7l5qB2AVBHPFQ6BpMneNX32Vq8mV3j0g01s63BBV/y1YjM6nfwsgH0jiuGBjmb3cBTf6TEuUs0gyq7m3oPl1QXeQBFGTeKDxuWalEOZnOAIqmVfzN8ztCkgSnishEVfcrgE0y7ZstmFQysRg19Ex1zK3vU0JLA98wPUrE9Bsj9VnKgqGdcrrS9lOyIImqTbfyE56hyS/t2Kw33AtCe5Wy4a8pljwjVXHmVsXVOmkOjd1pI3P1QzIO15GvHfoUUFaRC8GuNpNNfAzEO1ROvlCbrksms6Aw/ies7jQL7WyJxAYhpsyE8aCLpT5wM1FzTz3zd+Sw31oBdbyCNLD+Ar82KDBwJQ25503/ZMiZ6Cs8HbHklQC/CoyDEoDovv1ROBFVppOdjVFxC90Ucq3SZvZPao3rcZP3Nw/ObucvhOG2wtO/f4AuNleNvj/JPNQu7WA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
